### ISSUE TITLE
Sorting tables

### ISSUE THREAD

**Issue by duffymeg** [duffymeg/DEAuthorshipPoll#1]
Some of the tables are Likert-type variables (e.g., always, sometimes, never), but are sorting alphabetically. Need to figure out how to sort these properly. My initial (failed!) attempt at this starts on line 50 of the polldataanalysis.r file.

**Comment by ashander** [comment]
Fyi you can link to a specific line of a file by clicking on it in github. Here's the line you mentioned: https://github.com/duffymeg/DEAuthorshipPoll/blob/master/PollDataAnalysis.R#L50

**Comment by duffymeg** [comment]
That is good to know! Thank you!

**Comment by ashander** [comment]
What's the difference between the analyses in [PollDataAnalysis.R](https://github.com/duffymeg/DEAuthorshipPoll/blob/master/PollDataAnalysis.R) and [AuthorshipPollAnalysis.Rmd](https://github.com/duffymeg/DEAuthorshipPoll/blob/master/AuthorshipPollAnalysis.Rmd)?

They seem to overlap slightly but the .R does more, I think. It might be better to consolidate to one or the other. Or to lay out clearly the difference (e.g. in the README)

(This is sort of a separate issue, but good to sort out sooner vs later.)

**Comment by duffymeg** [comment]
One of the things I am still trying to figure out is not just the mechanics of using of R markdown, but also how (in a bigger sense than "how do I format X") and why. I'm still working on that! Right now, I've been trying things out in the .r file and then trying to take the things I'm happy(ish) with and put them into the .rmd file in a version that is closer to the story I could envision telling in a blog post. 

Based on your question, it seems like maybe it would be more common to just have it all in the Rmd file?

**Comment by ashander** [comment]
Ok, so the .R is a scratch pad of sorts to draft the .Rmd? That work flow makes sense to me! It just wasn't obvious from looking at the code, which led to my question.

I'm unsure what's more common. I do think it's easier to understand what's going on in a single script, either Rmd or R, but having a scratch pad makes plenty of sense.

**Comment by ashander** [comment]
For this issue, you can reorder the factor using something like (before line 50):

``` r
Reorder <- function(x, ordering=c(1, 3, 5, 4, 2))
  factor(x, levels(x)[ordering])

Interdisciplinarity$Interdisciplinary <- Reorder(Interdisciplinarity$Interdisciplinary)
```

**Comment by duffymeg** [comment]
Yes, a scratch pad is a good way of describing what I was using the .r file for. I will add a note to the readme about that.

And thanks for the suggestion on ordering!

**Comment by duffymeg** [comment]
Oh, hmmm, now that I've tried running it, it doesn't seem to be reordering things. So, I'm reopening this for now.

**Comment by ashander** [comment]
Oops! I forgot to actually reorder the table by the factor
