### ISSUE TITLE
adding plots for likert data

### ISSUE THREAD

**Issue by raynamharris** [duffymeg/DEAuthorshipPoll#6]
This is very cool!

For the past three days, I've been playing with some R code to plot likert data (see two [github](https://github.com/raynamharris/CCBB) [repos](https://github.com/raynamharris/NSB_surveys)).

Here is some code I adapted from my own scripts to plot you "interdisciplinary" likert data grouped by "youngold", "LastSenior", "WhereLive", and "BasicApplied". Its in a .txt file, but you can paste it into a new R script or append it to the end of yours.

[PollDataAnalysis_likert.txt](https://github.com/duffymeg/DEAuthorshipPoll/files/326243/PollDataAnalysis_likert.txt)
![likert_1234](https://cloud.githubusercontent.com/assets/7544197/16240494/7da8b584-37b7-11e6-9190-df3500e51fea.png)

**Comment by raynamharris** [comment]
Actually, I realized that "interdisciplinary" is far from a central point of your survey.  So I redid it. This shows that "youngold", "BasicApplied", and "deptype" don't really influence who people think should be corresponding author, but that there is some variability with "LastSenior", "WhereLive", and "PrimaryResearch
![corresponding_cowplot](https://cloud.githubusercontent.com/assets/7544197/16245438/e0800d30-37ce-11e6-8f50-35fcdb7ad0f5.png)
[PollDataAnalysis_likert.txt](https://github.com/duffymeg/DEAuthorshipPoll/files/326546/PollDataAnalysis_likert.txt)

**Comment by duffymeg** [comment]
Oh my goodness, this is amazing! Thank you! I was very, very slowly trying to work towards this!

**Comment by raynamharris** [comment]
No worries. They aren't perfect plots, but it is a nice start. You could also use ggplot stacked bar plots and/or facet wrap ([two](http://docs.ggplot2.org/0.9.3.1/geom_bar.html) [tutorials](http://swcarpentry.github.io/r-novice-gapminder/08-plot-ggplot2.html)) but I like how these likert plots are centered around the middle response for easier comparison.

**Comment by duffymeg** [comment]
Have you seen a way to leave off the legend? Since it's the same for all the panels, it seems like it would be better if I could hide it from 4-5 of the panels. Right now, all those legends take up a lot of figure space! (See below) I've tried looking some and haven't figured it out yet, so thought I'd check to see if you've already figured this out.

![lastplotgrid](https://cloud.githubusercontent.com/assets/8582090/16278651/b927a312-3885-11e6-9f1e-585db61cf00d.jpg)

**Comment by raynamharris** [comment]
Try adding this bit of code to the plots you want to put in panels A-D
`+ theme(legend.position = "none")`

For example
`plot(likert_12) + theme(legend.position = "none")`
`likert_12.mpg <- plot(likert_12) + theme(legend.position = "none")`

**Comment by duffymeg** [comment]
Oh, that was easy! I thought I needed to try to remove them sooner. Thank you!
